STATE:
  - VX
  - VY
  - YAW_RATE
  - STEERING_FB
ACTIONS:
  - STEERING_CMD
  - VREF
PARAMETERS:
  - Bf:
  - Cf:
  - Ef:
  - Br:
  - Cr:
  - Er:
  - Frx:
VEHICLE_SPECS:
  lf: 1.248
  lr: 1.7328
  mass: 790.0
  Iz: 1000.0
  h: 0.3
  L: 2.9808
  rho: 1.225
  g: 9.81
  A_f: 0.5
  A_r: 0.7
  C_lf: 1.5
  C_lr: 2.0
  mu: 1.5
MODEL:
  NAME: DeepPacejkaIAC
  HORIZON: 16
  LAYERS:
    - GRU:
      OUT_FEATURES: 256
      LAYERS: 5
    - DENSE:
      OUT_FEATURES: 254
      ACTIVATION: Mish
  OPTIMIZATION:
    LOSS: MSE
    BATCH_SIZE: 128
    NUM_EPOCHS: 400
    OPTIMIZER: Adam
    LR: 0.000439
