STATE:
  - VX
  - VY
  - YAW_RATE
  - THROTTLE_FB
  - STEERING_FB
ACTIONS:
  - THROTTLE_CMD
  - STEERING_CMD
PHYSICS_PARAMS:
  Bf: 5.579
  Cf: 1.2
  Ef: -0.083
  Br: 5.3852
  Cr: 1.2691
  Er: -0.019
  Cm1: 0.287
  Cm2: 0.0545
  Cr0: 0.0518
  Cr2: 0.00035
  Iz: 27.8e-6
  Shf: -0.0013
  Svf: 0.00043
  Shr: -0.00376
  Svr: 0.00091
VEHICLE_SPECS:
  lf: 0.029
  lr: 0.033
  mass: 0.041
  h: 0.01
  L: 0.062
  rho: 1.225
  g: 9.81
  A_f: 0.001
  A_r: 0.001
  C_lf: 0.0
  C_lr: 0.0
  mu: 0.8
  Iz: 27.8e-6
MODEL:
  NAME: DeepDynamicsPINN
  HORIZON: 5
  LAYERS:
    - GRU:
      OUT_FEATURES: 25
      LAYERS: 7
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
  OPTIMIZATION:
    LOSS: MSE
    BATCH_SIZE: 32
    NUM_EPOCHS: 400
    OPTIMIZER: Adam
    LR: 0.0006
    PHYSICS_LOSS_WEIGHT: 0.1
